### PR TITLE
Iudb16 send private message

### PR DESCRIPTION
**Pull request by danielqiuu**
Implemented sending private message. In a text chat, you can call the function by /send_private_discord_message [username] [message]

### CODE REVIEW

**Comment by Mustaballer** [comment]
@danielqiuu lgtm! What's left to do here?

**Comment by Mustaballer** [comment]
@danielqiuu Can you make it so this command is limited to users with a specific role, ex. Hackathon Director? You can refer to last years discord bot [repo](https://github.com/jhimanish/discord-hackathon-bot) for inspiration.

**Comment by danielqiuu** [comment]
> @danielqiuu Can you make it so this command is limited to users with a specific role, ex. Hackathon Director? You can refer to last years discord bot [repo](https://github.com/jhimanish/discord-hackathon-bot) for inspiration.

Yes I can look into doing this. If im not mistaken, I would need to know the role name so that the bot can recognize who to honour the command to. I can make it such that if the role contains the word "IEEE" then it will honour the command. How does that sound?

**Comment by Mustaballer** [comment]
Could you make it "Hackathon Director" as it matches with this [PR](https://github.com/ieeeuoft/IEEE-UofT-Discord-Bot/pull/6/files).

**Comment by danielqiuu** [comment]
image

**Comment by danielqiuu** [comment]
image

**Comment by Mustaballer** [comment]
@danielqiuu This looks great, the only suggestion I have is to create docstrings for each function, preferrably using [google python style docstrings](https://google.github.io/styleguide/pyguide.html).

**Review by Mustaballer — APPROVED** [review]
Looks great!

**Pull request merged**
