### PR TITLE
IUDB5 - Creating Initializer scripts to setup Hackathon Server

### PR DESCRIPTION
**Pull request by jhimanish**
Creating the /hackathon_setup command which can be used to create the roles, channels, and categories

### CODE REVIEW

**Comment by Mustaballer** [comment]
@jhimanish lgtm! What's left to do?

**Comment by jhimanish** [comment]
> @jhimanish lgtm! What's left to do?

Currently there's still more roles that need to be added and I still have to set up the call to create all the channels. I was thinking that I would also set up the permissions for the channels too to match our old servers

**Comment by Mustaballer** [comment]
@jhimanish any update on this?

**Comment by jhimanish** [comment]
Yeah I'm still setting up all the roles and channels. I'm trying to figure out what channels need which permissions so that the verification thing can work properly when we set that up

**Comment by jhimanish** [comment]
This is how the bot works with the hackathon setup command. It creates all of the roles, channels, and categories. Short video showing how it works from scratch

https://github.com/ieeeuoft/IEEE-UofT-Discord-Bot/assets/54194957/0afaaffa-13b1-4f39-a1ca-50cd0c72a67f

**Review by Mustaballer — APPROVED** [review]
This is great! Great job!

**Pull request merged**
