### PR TITLE
New iudb 14 adding user roles

### PR DESCRIPTION
**Pull request by carmen-chau**
### Description: 
Preliminary implementation for **IDUB -14 : Add the role to the user** 

### Current assumptions:

- Assuming that whatever role the discord bot has CANNOT be assigned to any user. Doing so will return an error message (see end of video for more details)

### Features:

- Can process and assign multiple roles to a user 
- Can assign roles with a name containing 2+ worse 

### Sample calls:

See video + read docstring 

**NOTE:** I have made a change post-video recording to one of the bot's return messages. Whenever a user wants to assign a role that either does not exist in the server or they do not have access to, the returned message should now say: `Role: "xxx " is not a valid role to be assigned to.` where xxx denotes the name of the role

https://github.com/ieeeuoft/IEEE-UofT-Discord-Bot/assets/80921817/53499c96-c9c6-446f-a608-8a355669914f

### CODE REVIEW

**Comment by Mustaballer** [comment]
@carmen-chau Are you able to assign any roles with this function, even roles that have not been created yet? What's left to do here?

**Comment by Mustaballer** [comment]
Regarding the limitation you faced can you try this approach(ChatGPT)?
>We can use the commands.MemberConverter() to try converting the given username to a valid member object. If the conversion fails, it means the username is invalid, and we can display the "invalid username" error message.


```python
    @commands.command()
    async def assign_role(self, ctx, username, *roles):
        try:
            member = None
            try:
                member = await commands.MemberConverter().convert(ctx, username)
            except commands.MemberNotFound:
                await ctx.send("Invalid username. User not found.")
                return
            
            if not roles:
                await ctx.send(f"{username}, you did not specify a role to assign. Please try again.")
            else:
                channel = ctx.guild
                set_of_curr_member_roles = {role.name for role in member.roles}
                set_of_valid_channel_roles = {role.name for role in channel.roles}
                set_of_desired_roles = set(roles) & set_of_valid_channel_roles

                if not set_of_desired_roles:
                    await ctx.send(f"{username}, these roles do not exist. Please try again")
                else:
                    for role in set_of_desired_roles:
                        if role not in set_of_curr_member_roles:
                            assigned_role = discord.utils.get(channel.roles, name=role)
                            print("Assigned role: ", assigned_role)
                            try:
                                await member.add_roles(assigned_role)
                                await ctx.send(f"Assigned role: {role}")
                            except Exception as e:
                                print(f"Error occurred with assigning role: {e}")
                        else:
                            await ctx.send(f"{username}, you already have the role: {role}")
        except Exception as e:
            await ctx.send(f"Error occurred with command call: {e}")

```

**Comment by carmen-chau** [comment]
> @carmen-chau Are you able to assign any roles with this function, even roles that have not been created yet? What's left to do here?

1. No, we cannot assign "any role" with this function. Only roles that (at the time of calling the discord bot method in the server) will be enabled for assignment to users. If the role does not exist, an error message will be displayed to the user, saying "these roles do not exist. Please try again"
2. In terms of what is left to do, will need to look into restricting this role assignment process to only channel moderators and/or administrators. Will need to consult with @jhimanish's current PR and past discord repo for more info on this.

**Comment by carmen-chau** [comment]
Note: I tested the `assign_role` method on a cloned version of #3 and I was able to call the command as intended. However, running the method on this branch and on a fresh branch  directly created from`develop` resulted in the following error:

Screenshot 2023-08-05 at 9 01 07 PM

Not entirely sure what causes this issue, any thoughts or debugging tips appreciated

**Comment by Mustaballer** [comment]
@carmen-chau Referring to #3, can you try this approach?

```python
def is_allowed_role():
        async def predicate(ctx):
            allowed_role = discord.utils.get(ctx.guild.roles, name='Hackathon Director')
            return allowed_role in ctx.author.roles
        return commands.check(predicate)

@commands.command()
@is_allowed_role()  # Modify this line
# your function
```

**Review by Mustaballer — APPROVED** [review]
lgtm!

**Pull request merged**
